// auto generated content from display configuration
import QtQuick 2.2
import QtQuick.Window 2.0
import QtQuick.Controls 1.1
import QtQuick.Controls.Styles 1.1
import QtQuick.Extras 1.4

TXTWindow {
  Rectangle {
    id: rect
    color: "grey"
    anchors.fill: parent
  }
  TXTButton {
    id: a_upper
    text: "A"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 10
    width: 35
    height: 26
  }
  TXTButton {
    id: b_upper
    text: "B"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: c_upper
    text: "C"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 100
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: d_upper
    text: "D"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 145
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: e_upper
    text: "E"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 190
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: f_upper
    text: "F"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 44
    width: 35
    height: 25
  }
  TXTButton {
    id: g_upper
    text: "G"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: h_upper
    text: "H"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 100
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: i_upper
    text: "I"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 146
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: j_upper
    text: "J"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 190
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: k_upper
    text: "K"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: l_upper
    text: "L"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: m_upper
    text: "M"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 100
    y: 80
    width: 36
    height: 25
  }
  TXTButton {
    id: n_upper
    text: "N"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 145
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: o_upper
    text: "O"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 190
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: p_upper
    text: "P"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: q_upper
    text: "Q"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: r_upper
    text: "R"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 100
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: s_upper
    text: "S"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 145
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: t_upper
    text: "T"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 190
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: u_upper
    text: "U"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: v_upper
    text: "V"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: w_upper
    text: "W"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 98
    y: 150
    width: 39
    height: 25
  }
  TXTButton {
    id: x_upper
    text: "X"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 145
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: y_upper
    text: "Y"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 190
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: z_upper
    text: "Z"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 10
    y: 185
    width: 35
    height: 25
  }
  TXTButton {
    id: shift_lower
    text: "abc..."
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 145
    y: 185
    width: 80
    height: 25
  }
  TXTButton {
    id: space
    text: "Space"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: true
    x: 55
    y: 185
    width: 80
    height: 25
  }
  TXTButton {
    id: a_lower
    text: "a"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: b_lower
    text: "b"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 55
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: c_lower
    text: "c"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 100
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: d_lower
    text: "d"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: e_lower
    text: "e"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 190
    y: 10
    width: 35
    height: 25
  }
  TXTButton {
    id: f_lower
    text: "f"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: g_lower
    text: "g"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 55
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: h_lower
    text: "h"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 100
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: i_lower
    text: "i"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: j_lower
    text: "j"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 190
    y: 45
    width: 35
    height: 25
  }
  TXTButton {
    id: k_lower
    text: "k"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: l_lower
    text: "l"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 55
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: m_lower
    text: "m"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 100
    y: 80
    width: 36
    height: 25
  }
  TXTButton {
    id: n_lower
    text: "n"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: o_lower
    text: "o"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 190
    y: 80
    width: 35
    height: 25
  }
  TXTButton {
    id: p_lower
    text: "p"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: q_lower
    text: "q"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 55
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: r_lower
    text: "r"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 100
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: s_lower
    text: "s"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: t_lower
    text: "t"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 190
    y: 115
    width: 35
    height: 25
  }
  TXTButton {
    id: u_lower
    text: "u"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: v_lower
    text: "v"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 55
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: w_lower
    text: "w"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 100
    y: 150
    width: 39
    height: 25
  }
  TXTButton {
    id: x_lower
    text: "x"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: y_lower
    text: "y"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 190
    y: 150
    width: 35
    height: 25
  }
  TXTButton {
    id: z_lower
    text: "z"
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 10
    y: 185
    width: 35
    height: 25
  }
  TXTButton {
    id: shift_upper
    text: "ABC..."
    font.pixelSize: 32
    font.bold: false
    font.italic: false
    font.underline: false
    enabled: false
    x: 145
    y: 185
    width: 80
    height: 25
  }
}
